[workspace]
members = [
    "crates/metal-infer-cli",
    "crates/metal-infer-kernels",
    "crates/metal-infer-models",
    "crates/metal-infer-planner",
    "crates/metal-infer-runtime",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"

[workspace.dependencies]
clap = { version = "4.6.7", features = ["derive"] }
half = "2.7.1"
objc2 = "0.6.4"
objc2-foundation = { version = "0.3.2", features = ["NSString"] }
objc2-metal = "0.3.2"
objc2-metal-performance-shaders = { version = "0.3.2", features = [
    "MPSCore",
    "MPSCoreTypes",
    "MPSKernel",
    "MPSMatrix",
    "MPSMatrixMultiplication",
] }
safetensors = "0.8.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.20"
tokenizers = { version = "0.23.2", default-features = false, features = ["onig"] }

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
uninlined_format_args = "deny"
missing_assert_message = "deny"
self_named_module_files = "deny"
wildcard_imports = "deny"
semicolon_outside_block = "deny"
single_char_lifetime_names = "deny"
str_to_string = "deny"
unwrap_used = "deny"
new_without_default = "allow"
indexing_slicing = "deny"
fallible_impl_from = "deny"
wildcard_enum_match_arm = "deny"
unneeded_field_pattern = "deny"
fn_params_excessive_bools = "deny"
struct_field_names = "allow"
