[package]
name = "metal-infer-models"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
half.workspace = true
metal-infer-kernels = { path = "../metal-infer-kernels" }
metal-infer-runtime = { path = "../metal-infer-runtime" }
safetensors.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokenizers.workspace = true

[lints]
workspace = true
